#!/bin/bash

# meta/config

# Generate config.json adding defaults to config.yaml

# Usage: config config.yaml > config.json

CONFIG=${1?Expected config.yaml}

yaml2json $CONFIG \
| jq --sort-keys --from-file ${0}.jq

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
