#!/bin/bash

# meta/node

# Merge 'node.json'from config.json

# Usage: node config.json 'node.json' > 'node.json'

CONFIG=${1?Expected config.json}
TARGET=${1?Expected target pathname}

prefix=${TARGET%.json}
TITLE=${prefix##*/}
ID=${prefix#*/nodes/}/index

jq  --sort-keys			                    \
    --from-file ${0}.jq                     \
    --arg id $ID                            \
    --arg title $TITLE
    $CONFIG

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
