#!/bin/bash

# meta/site

# Create site.json

# Usage: site config.json version > site.json

CONFIG=$1
VERSION=$2

jq  --sort-keys				\
    --from-file ${0}.jq     \
    --arg version $VERSION  \
    "$CONFIG"

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
