#!/bin/bash

# meta/config

# Generate config.json adding defaults to config.yaml

# Usage: config config.yaml > config.json

CONFIG='-'

jq --sort-keys --from-file ${0}.jq $CONFIG

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
