#!/bin/bash

# meta/page

# Merge page front-matter with defaults and etc.

# Usage: page config.json 'source' 'stem' 'target'

CONFIG=$1
SOURCE=$2
TARGET=$3

front_matter='-'    # standard input
lastmod=$(date --utc --iso-8601=seconds --reference=$SOURCE)
id=${TARGET%.json}; id=${id#*/pages/}
filename=${id##*/}
path=${id%$filename}
section=${path%%/*}
base=$(sed 's/[^/]\+/../g;s/\.\.$//' <<<"$id")

jq  --sort-keys			            \
    --slurpfile config $CONFIG      \
    --from-file ${0}.jq             \
    --arg id $id                    \
    --arg filename $filename        \
    --arg base "$base"              \
    --arg lastmod $lastmod          \
    --arg path "$path"              \
    --arg section "$section"        \
    $front_matter

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
