#!/bin/bash

# meta/pages

# Concat all individual JSON pages as a list

# Usage: pages {page.json...} > pages.json

jq  --sort-keys         \
    --slurp             \
    --from-file ${0}.jq \
    "$@"

exit

# TODO: use xargs or equivalent?

# vim:ts=4:sw=4:ai:et:syntax=sh
