#!/bin/bash

# meta/site

# Create site.json

# Usage: site config.json version > site.json

CONFIG=${1?Expected config.json}
VERSION=${1?Expected version code}

jq  --from-file ${0}.jq     \
    --arg version $VERSION  \
    "$CONFIG"

exit

# vim:ts=4:sw=4:ai:et:syntax=sh
